### PR TITLE
Added Email for Editing User.

### LINKED ISSUE #239: Editing User Does not Display Username
## Summary of the Bug
The Editing User Page Does not Display a username. Though, change the role of a user may be reversible, it may not be desirable to do so accidentally.  

## The Expected Behaviour
The Editing User Page Should tell what user is being modified.

## Screenshots
Screenshot from 2021-06-20 16-54-32

### PR DESCRIPTION
**Pull request by EarthSchlange**
## Summary
Resolves #239

### CODE REVIEW

**Comment by neagle** [comment]
This is a great starter PR. Thanks for getting involved!

There are a few issues:

* Users and attendees are different: a user is an email, a password, and a role. When editing the user role, the only identification you really have that you could display would be the email address.
* Tests are your friend! You should run `bin/rspec` to go through the test suite once you've made changes that you're ready to commit. In this case, the test suite flags a bunch of breakages caused by the change to the users controller.
* @jaredbeck has also hooked us up with a replacement to Travis CI so that we can run the test suite through Github Actions for each pull request, so you can see when you looking at any PR whether it's past the tests or not.

**Review by neagle — CHANGES_REQUESTED** [review]
Need to switch to using the user email address, rather than attendee name information, and make sure tests pass.

**Comment by EarthSchlange** [comment]
Thank you for the information on rspec. Change to user email. It looks like only the UserController tests needed to pass, so `$ rspec spec/controllers/users_controller_spec.rb` seems to work for testing a single controller test.

**Comment by EarthSchlange** [comment]
Changed title to reflect current limitations of User.

**Review by jaredbeck — APPROVED** [review]

**Comment by jaredbeck** [comment]
👍

**Pull request merged**
